/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    blogs: Blog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'home-page': HomePage;
    'principles-page': PrinciplesPage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'principles-page': PrinciplesPageSelect<false> | PrinciplesPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO. Be specific; skip “image of”. e.g. “Therapist and child playing with letter cards”.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  /**
   * Post title. The URL slug is generated from this automatically.
   */
  title: string;
  slug: string;
  /**
   * One or two sentences (max ~160 characters). Shown on blog cards and used as the search/social preview.
   */
  description: string;
  /**
   * Full article body. Use headings and lists to break up long sections.
   */
  details: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Featured image, landscape 4:3, ≥1200px wide, under ~300 KB.
   */
  image: number | Media;
  /**
   * Date shown on the post and used to sort the blog list (newest first).
   */
  publishedDate: string;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  details?: T;
  image?: T;
  publishedDate?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Header logo. Transparent PNG/SVG, roughly 200×60, under ~50 KB.
   */
  logo: number | Media;
  /**
   * Phone call-to-action shown in the header.
   */
  hotline: {
    /**
     * Number as displayed, e.g. (555) 123-4567.
     */
    number: string;
    /**
     * Click target — use a tel: link, e.g. tel:+15551234567.
     */
    link: string;
  };
  /**
   * Main navigation links, in order. Use #section for home-page anchors (e.g. #contact) or a path like /blog.
   */
  navLinks?:
    | {
        /**
         * Link text shown in the menu.
         */
        label: string;
        /**
         * Destination: /path, #section, or full URL.
         */
        link: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Footer logo. A light/white version reads best on the dark footer.
   */
  logo: number | Media;
  /**
   * Footer navigation links, in order.
   */
  navLinks?:
    | {
        /**
         * Link text.
         */
        label: string;
        /**
         * Destination: /path, #section, or full URL.
         */
        link: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Copyright line, e.g. “© 2026 Liberation Language Labs”.
   */
  copyright: string;
  /**
   * Optional credit text, e.g. “Designed by …”.
   */
  designerText?: string | null;
  /**
   * Optional URL the credit text links to.
   */
  designerLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * The first thing visitors see. Keep it short, warm, and affirming.
   */
  hero: {
    /**
     * Main headline overlaid on the hero image. Aim for 3–7 words.
     */
    title: string;
    /**
     * Wide hero image, ≥1920×1080, under ~400 KB. Keep the subject toward the left — the headline overlays the right side.
     */
    backgroundImage: number | Media;
  };
  /**
   * Introduces the practice and its approach.
   */
  about: {
    /**
     * Section heading, e.g. “About the Labs”.
     */
    title: string;
    /**
     * Optional short line shown above or below the title.
     */
    subtitle?: string | null;
    /**
     * Two to three short paragraphs. Plain, affirming language reads best here.
     */
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Portrait/lifestyle image, roughly square or 4:3, under ~300 KB.
     */
    image: number | Media;
  };
  /**
   * Highlights the speech-therapy focus areas.
   */
  speechTherapy: {
    /**
     * Section heading.
     */
    title: string;
    /**
     * Optional 1–2 sentence intro under the heading.
     */
    description?: string | null;
    /**
     * Each row is one focus area. 3–6 rows works best visually.
     */
    items?:
      | {
          /**
           * Short label, 1–4 words.
           */
          title: string;
          /**
           * One or two sentences describing this focus area.
           */
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Grouped lists of services offered.
   */
  services: {
    /**
     * Section heading.
     */
    title: string;
    /**
     * Optional intro under the heading.
     */
    description?: string | null;
    /**
     * Each row is a service group (a column of related services).
     */
    servicesLists?:
      | {
          /**
           * Heading for this group of services.
           */
          listTitle: string;
          /**
           * Individual services listed under this group.
           */
          listItems?:
            | {
                /**
                 * One service. Keep it to a short phrase.
                 */
                item: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Pricing and payment details.
   */
  pricing: {
    /**
     * Section heading.
     */
    title: string;
    /**
     * Optional intro under the heading.
     */
    description?: string | null;
    /**
     * Payment/insurance details. Use a bullet list for sliding-scale or accepted plans.
     */
    paymentInfo?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Contact details shown in the home page contact block. Leave a field blank to hide its card.
   */
  contactInfo: {
    /**
     * Section heading, e.g. “Get in touch”.
     */
    title: string;
    /**
     * Optional intro under the heading.
     */
    description?: string | null;
    /**
     * Display format, e.g. (555) 123-4567.
     */
    phone?: string | null;
    /**
     * Optional. Leave blank to hide the Fax card.
     */
    fax?: string | null;
    /**
     * Public contact email, e.g. hello@liberationlabs.com.
     */
    email?: string | null;
    /**
     * Single-line mailing address.
     */
    address?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "principles-page".
 */
export interface PrinciplesPage {
  id: number;
  /**
   * Top banner of the Principles page.
   */
  banner: {
    /**
     * Page banner heading.
     */
    title: string;
  };
  /**
   * Opening statement of principles.
   */
  statement: {
    /**
     * Section heading.
     */
    title: string;
    /**
     * The statement body. Short paragraphs read best.
     */
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  /**
   * Your commitment to clients.
   */
  commitment: {
    /**
     * Section heading.
     */
    title: string;
    /**
     * The commitment body.
     */
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  /**
   * “What we strive for” — an optional heading, bullet list, and closing text.
   */
  strive?: {
    /**
     * Optional section heading.
     */
    title?: string | null;
    /**
     * Each row is one bullet point.
     */
    list?:
      | {
          /**
           * A single bullet. Keep it to one line.
           */
          item: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional closing paragraph below the list.
     */
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  hotline?:
    | T
    | {
        number?: T;
        link?: T;
      };
  navLinks?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  navLinks?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  copyright?: T;
  designerText?: T;
  designerLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        backgroundImage?: T;
      };
  about?:
    | T
    | {
        title?: T;
        subtitle?: T;
        description?: T;
        image?: T;
      };
  speechTherapy?:
    | T
    | {
        title?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        title?: T;
        description?: T;
        servicesLists?:
          | T
          | {
              listTitle?: T;
              listItems?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  pricing?:
    | T
    | {
        title?: T;
        description?: T;
        paymentInfo?: T;
      };
  contactInfo?:
    | T
    | {
        title?: T;
        description?: T;
        phone?: T;
        fax?: T;
        email?: T;
        address?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "principles-page_select".
 */
export interface PrinciplesPageSelect<T extends boolean = true> {
  banner?:
    | T
    | {
        title?: T;
      };
  statement?:
    | T
    | {
        title?: T;
        content?: T;
      };
  commitment?:
    | T
    | {
        title?: T;
        content?: T;
      };
  strive?:
    | T
    | {
        title?: T;
        list?:
          | T
          | {
              item?: T;
              id?: T;
            };
        content?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}